### PR TITLE
leave space in between comma

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
I think it's better to leave a space between comma's as it looks better, in my opinion :)

### CODE REVIEW

**Comment by jaynarayan-vaishnav** [comment]
This the branch name is causing a conflict.

**Review by jaynarayan-vaishnav — DISMISSED** [review]

**Comment by KendallDoesCoding** [comment]
> This the branch name is causing a conflict.

Yeah coz my other PR which you merged, hasn't been updated to this branch.

**Comment by KendallDoesCoding** [comment]
> This the branch name is causing a conflict.

Yeah coz my other PR which you merged, hasn't been updated to this branch.

**Comment by KendallDoesCoding** [comment]
idk what the issue is and dont know how to resolve the conflict, will make a new PR in a bit, please keep this open.

**Comment by jaynarayan-vaishnav** [comment]
okay

**Comment by jaynarayan-vaishnav** [comment]
i thinks the problem is with the (opensource word) yow have resolved it in a previous pr but doing it again now. just check the changes made section

**Comment by jaynarayan-vaishnav** [comment]
refer the #2  issue

**Comment by jaynarayan-vaishnav** [comment]
I have resolved the conflict thanks for contributing but next time please check the code first so as to not cause the conflict.

**Review by jaynarayan-vaishnav — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
> I have resolved the conflict thanks for contributing but next time please check the code first so as to not cause the conflict.

Great... Thanks a lot, the issue happens very often when there are multiple PR's, if you merged this first, my other PR would have had conflicts coz I edited the same file.

In future, I'll make one PR at a time.

Thanks a lot!!

**Pull request merged**
